#ifndef PYPREFERENCE_H__
#define PYPREFERENCE_H__

enum
{
	BOGHMA_PYPREFERENCE_MAIN_GROUP						= 999,	

	BOGHMA_PYPREFERENCE_SHOW_IN_TOPMENU					= 1000,
	BOGHMA_PYPREFERENCE_ASSET_FOLDER					= 1001,

	BOGHMA_PYPREFERENCE_UPDATE_GROUP					= 1002,	
	BOGHMA_PYPREFERENCE_CUSTOM_UPDATE 					= 1003,
	BOGHMA_PYPREFERENCE_UPDATE_SETTING			 		= 1004,
		BOGHMA_PYPREFERENCE_UPDATE_START 			= 0,
		BOGHMA_PYPREFERENCE_UPDATE_OPEN_MANAGER 	= 1,
		BOGHMA_PYPREFERENCE_UPDATE_CHECK_BUTTON		= 2,
	BOGHMA_PYPREFERENCE_TIME_INTERVAL					= 1005,
	BOGHMA_PYPREFERENCE_BUTTON 							= 1006,
	BOGHMA_PYPREFERENCE_SIZE							= 1007,


	PYPREFERENCE_DUMMY
};

#endif // PYPREFERENCE_H__
